// Admin UI strings. Every key exists in both EN and UK — TypeScript enforces
// that `uk` has at least every key `en` has (see AdminLang.tsx).
// Placeholders like {n} / {name} are filled with `fmt()` from AdminLang.

const en = {
  // ── Shell / navigation ──────────────────────────────────────────────
  studioAdmin: 'Studio Admin',
  adminTitle: 'Admin',
  navDashboard: 'Dashboard',
  navReviews: 'Reviews',
  navServices: 'Services',
  navBio: 'Bio',
  navGallery: 'Gallery',
  navBrands: 'Brands',
  navBookings: 'Bookings',
  navMessages: 'Messages',
  navContact: 'Contact',
  navDomain: 'Domain',
  navSettings: 'Settings',
  navTrash: 'Trash',
  navMore: 'More',
  groupOverview: 'Overview',
  groupInbox: 'Inbox',
  groupWebsite: 'Website',
  groupSetup: 'Setup',
  viewWebsite: 'View website',
  website: '← Website',
  account: 'Account',
  signedInAs: 'Signed in as',
  logout: 'Log out',
  adminLanguage: 'Admin language',
  dbUpdateTitle: 'Database update needed',
  dbUpdateBody:
    'Run supabase/migrations/20260916_admin_redesign.sql in the Supabase SQL editor to enable statuses, notes, Trash and the new booking form fields. Until then this screen works in compatibility mode.',

  // ── Common UI ───────────────────────────────────────────────────────
  loading: 'Loading…',
  retry: 'Retry',
  errorTitle: 'Something went wrong',
  errorBody: 'We couldn’t load this. Check your connection and try again.',
  close: 'Close',
  back: 'Back',
  done: 'Done',
  undo: 'Undo',
  copy: 'Copy',
  copied: 'Copied',
  search: 'Search',
  filters: 'Filters',
  clearFilters: 'Clear filters',
  apply: 'Apply',
  select: 'Select',
  selectAll: 'Select all',
  selectedCount: '{n} selected',
  refresh: 'Refresh',
  saveChanges: 'Save changes',
  saved: 'Saved',
  unsavedTitle: 'Unsaved changes',
  unsavedBody: 'You have changes that haven’t been saved. Leave anyway?',
  leave: 'Leave',
  stay: 'Stay',
  toastSaved: '✓ Saved',
  toastError: 'Couldn’t save. Please try again.',
  toastUpdated: '✓ Updated',
  yes: 'Yes',
  no: 'No',
  none: 'None',
  optional: 'Optional',
  required: 'Required',
  showMore: 'Show more',
  showLess: 'Show less',
  today: 'Today',
  tomorrow: 'Tomorrow',
  yesterday: 'Yesterday',
  noDate: 'No date',
  timeNotChosen: 'time not chosen',
  save: 'Save',
  cancel: 'Cancel',
  add: 'Add',
  edit: 'Edit',
  delete: 'Delete',
  replace: 'Replace',
  remove: 'Remove',
  uploadImage: 'Upload image',
  uploading: 'Uploading…',
  livePreview: 'Live preview',
  weekdayShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  weekdayLong: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],

  // ── Auth ────────────────────────────────────────────────────────────
  signIn: 'Sign in',
  signInSubtitle: 'Authorized access only',
  emailPlaceholder: 'Email',
  password: 'Password',
  passwordPlaceholder: 'Password',
  loginBtn: 'Sign in',
  signingIn: 'Signing in…',
  incorrectPassword: 'Incorrect email or password',
  notAuthorized: 'This account is not authorized for admin access.',
  checkingSession: 'Checking session…',

  // ── Bookings ────────────────────────────────────────────────────────
  bookingsTitle: 'Bookings',
  bookingsIntro: 'Requests from the website’s Book button.',
  viewInbox: 'Inbox',
  viewCalendar: 'Calendar',
  viewClients: 'Clients',
  segNeedsAction: 'Needs action',
  segConfirmed: 'Confirmed',
  segPast: 'Past',
  segArchived: 'Archived',
  segAll: 'All',
  sortNeedsFirst: 'Needs action first',
  sortNewest: 'Newest submitted',
  sortLabel: 'Sort',
  searchBookings: 'Search name, phone, email or service',
  filterStatus: 'Status',
  filterService: 'Service',
  filterFrom: 'From',
  filterTo: 'To',
  filterAnyStatus: 'Any status',
  filterAnyService: 'Any service',
  filterDateRange: 'Preferred date',
  statusNew: 'New',
  statusContacted: 'Contacted',
  statusConfirmed: 'Confirmed',
  statusCompleted: 'Completed',
  statusDeclined: 'Declined',
  statusCancelled: 'Cancelled',
  statusNoShow: 'No-show',
  statusArchived: 'Archived',
  badgeReplyToday: 'Reply today',
  badgeExpired: 'Expired',
  badgeConflict: 'Time conflict',
  badgeReturning: 'Returning · {n} visits',
  badgeReturningRequests: 'Returning · {n} requests',
  badgeNewClient: 'New client',
  badgeSubmissions: '×{n} submissions',
  badgeUnread: 'Unread',
  badgeNoTime: 'No time chosen',
  badgeOutsideHours: 'Outside hours',
  badgeClosedDay: 'Closed that day',
  summaryReplyToday: '{n} need a reply today',
  summaryDuplicates: '{n} duplicates merged',
  summaryConflicts: '{n} time conflicts',
  summaryConfirmedWeek: '{n} confirmed this week',
  summaryAllClear: 'All caught up ✦',
  preferred: 'Preferred',
  submitted: 'Submitted',
  via: 'via',
  methodSms: 'Text',
  methodInstagram: 'Instagram',
  methodEmail: 'Email',
  methodCall: 'Call',
  requestDetails: 'Request',
  client: 'Client',
  contact: 'Contact',
  actionText: 'Text',
  actionCall: 'Call',
  actionEmail: 'Email',
  noPhoneCaptured: 'No phone captured (older request). Ask for it in your reply.',
  service: 'Service',
  price: 'Price',
  duration: 'Duration',
  minutesShort: '{n} min',
  preferredTime: 'Preferred time',
  alsoOk: 'Also OK',
  optionsFromSubmissions: 'Times from the {n} submissions',
  clientMessage: 'Client’s message',
  siteLanguage: 'Site language',
  clientHistory: 'Client history',
  requestsCount: '{n} requests',
  visitsCount: '{n} visits',
  upcomingCount: '{n} upcoming',
  lastService: 'Last service',
  lastVisit: 'Last visit',
  firstRequest: 'First request',
  privateNotes: 'Private notes',
  notesPlaceholder: 'Only you can see this. Allergies, preferences, reminders…',
  notesSaving: 'Saving…',
  notesSaved: 'Saved',
  activity: 'Activity',
  noActivity: 'No activity yet.',
  evCreated: 'Request received',
  evResubmitted: 'Submitted again',
  evStatus: '{from} → {to}',
  evContacted: 'You reached out ({channel}: {kind})',
  evNote: 'Note',
  evMerged: 'Merged into another request',
  evMergedIn: 'Duplicates merged into this request',
  evTrashed: 'Moved to Trash',
  evRestored: 'Restored from Trash',
  evRescheduled: 'Time changed',
  actConfirm: 'Confirm',
  actSuggest: 'Suggest another time',
  actDecline: 'Decline',
  actComplete: 'Mark completed',
  actNoShow: 'Mark no-show',
  actArchive: 'Archive',
  actFollowUp: 'Follow up',
  actReopen: 'Reopen',
  actCancelAppt: 'Cancel appointment',
  actMarkRead: 'Mark read',
  actMarkUnread: 'Mark unread',
  actDelete: 'Delete',
  actRestore: 'Restore',
  actDeleteForever: 'Delete permanently',
  actReminder: 'Send reminder',
  actRequestReview: 'Request a review',
  actMore: 'More actions',
  actExportCsv: 'Export CSV',
  actDownloadIcs: 'Add to calendar (.ics)',
  actAi: 'AI assist',
  confirmTitle: 'Confirm appointment',
  confirmFor: 'Confirm for',
  confirmAndText: 'Confirm & open text',
  confirmAndEmail: 'Confirm & open email',
  confirmOnly: 'Confirm without a message',
  chooseTime: 'Choose a time',
  anotherTime: 'Another time…',
  suggestTitle: 'Suggest another time',
  suggestHint: 'Pick up to 3 open slots to offer the client.',
  nextOpen: 'Next open slots',
  noOpenSlots: 'No open slots in the next weeks. Adjust hours in Contact.',
  openMessages: 'Open Messages',
  openEmail: 'Open email',
  openInstagram: 'Open Instagram',
  messagePreview: 'Message',
  editMessage: 'Edit before sending — nothing is sent automatically.',
  declineTitle: 'Decline request',
  declineHint: 'The client gets your message; the request moves to Declined.',
  deleteTitle: 'Delete request?',
  deleteBody: 'It moves to Trash for 30 days, then it’s gone.',
  deletedToast: 'Moved to Trash',
  restoredToast: 'Restored',
  purgeTitle: 'Delete permanently?',
  purgeBody: 'This cannot be undone.',
  conflictConfirmed: 'Overlaps a confirmed appointment with {name}',
  conflictPending: 'Overlaps a pending request from {name}',
  conflictOutside: 'Outside business hours',
  conflictBlackout: 'Falls on a closed day',
  conflictBlocked: 'Overlaps blocked time',
  duplicatesTitle: 'Submissions',
  duplicatesHint: 'The client sent this {n} times. Only one card is shown; nothing was deleted.',
  aiSummary: 'Summary',
  aiDraft: 'Draft reply',
  aiGenerate: 'Draft with AI',
  aiWorking: 'Thinking…',
  aiUseDraft: 'Use this draft',
  bulkMarkRead: 'Mark read',
  bulkArchive: 'Archive',
  bulkDelete: 'Delete',
  calDay: 'Day',
  calWeek: 'Week',
  calToday: 'Today',
  calPrev: 'Previous',
  calNext: 'Next',
  calPending: 'Pending',
  calConfirmed: 'Confirmed',
  calBlocked: 'Blocked',
  calClosed: 'Closed',
  calNothing: 'Nothing scheduled',
  calBlockTime: 'Block off time',
  clientsSearch: 'Search clients',
  clientRequests: 'Requests',
  clientVisits: 'Visits',
  clientUpcoming: 'Upcoming',
  clientNone: 'No clients yet',
  clientNoneBody: 'Clients appear here once booking requests come in.',
  clientSince: 'Client since',
  emptyInboxTitle: 'Inbox zero ✦',
  emptyInboxBody: 'New booking requests from the website will show up here.',
  emptySegment: 'Nothing here',
  emptySegmentBody: 'Requests move here as their status changes.',
  emptySearch: 'No matches for “{q}”',
  emptySearchBody: 'Try a name, phone number, email or service.',
  trashTitle: 'Trash',
  // ---- settings
  settingsTitle: 'Settings',
  settingsIntro: 'Account, booking rules, notifications and reply templates.',
  secAccount: 'Account',
  changePassword: 'Change password',
  newPassword: 'New password',
  confirmPassword: 'Confirm new password',
  passwordMismatch: 'The passwords don’t match.',
  passwordTooShort: 'Use at least 8 characters.',
  passwordUpdated: 'Password updated',
  updatePassword: 'Update password',
  twoFactor: 'Two-factor authentication',
  twoFactorOnHint: 'On — a code from your authenticator app is required to sign in.',
  twoFactorOffHint: 'Off — only your password protects the admin.',
  twoFactorEnable: 'Set up 2FA',
  twoFactorDisable: 'Turn off 2FA',
  twoFactorScan: 'Scan this QR code with an authenticator app (Google Authenticator, 1Password, Authy), then enter the 6-digit code it shows.',
  twoFactorSecret: 'Or type this key into the app',
  twoFactorCode: 'Code from the app',
  twoFactorVerify: 'Verify & turn on',
  twoFactorInvalid: 'That code didn’t work. Wait for the next one and try again.',
  twoFactorWarning: 'Keep the authenticator safe: without it you can’t sign in. If it’s lost, the factor can be removed in the Supabase dashboard (Authentication → Users).',
  twoFactorDisableConfirm: 'Turn off two-factor authentication? Sign-in will only need the password.',
  mfaTitle: 'Two-factor code',
  mfaBody: 'Enter the 6-digit code from your authenticator app.',
  mfaSubmit: 'Verify',
  sessions: 'Sessions',
  signOutOthers: 'Sign out other devices',
  signOutOthersHint: 'Ends every session except this one.',
  signedOutOthers: 'Other devices signed out',
  secBookingRules: 'Booking rules',
  minNotice: 'Minimum notice (hours)',
  minNoticeHint: 'Clients can’t pick a time sooner than this.',
  maxDaysAhead: 'Book up to (days ahead)',
  slotMinutes: 'Time-slot step (minutes)',
  defaultBuffer: 'Default buffer between appointments (minutes)',
  defaultBufferHint: 'Used when a service has no buffer of its own.',
  autoArchiveDays: 'Auto-archive finished requests after (days)',
  autoArchiveHint: 'Completed, declined, cancelled and no-show requests move to Archived. 0 turns this off.',
  trashRetention: 'Keep trash for (days)',
  reviewsNeedApproval: 'Reviews need approval before they show on the website',
  secNotifications: 'Notifications',
  notifyNewBooking: 'Email me for each new booking request',
  notifyNewReview: 'Email me for each new review',
  notifyNewMessage: 'Email me for each new message',
  notifyEmail: 'Send notifications to',
  notifyEmailHint: 'Leave blank to use the studio email from Contact.',
  notifyNotConfigured: 'Email sending isn’t set up yet (RESEND_API_KEY). Notifications start once it is.',
  notifyConfigured: 'Email sending is set up.',
  secTemplates: 'Reply templates',
  templatesHint: 'Used by Confirm, Suggest a time, Decline, Reminder and Ask for a review. Tap a placeholder to insert it where the cursor is.',
  tplConfirm: 'Confirm',
  tplSuggest: 'Suggest a time',
  tplDecline: 'Decline',
  tplReminder: 'Reminder',
  tplReview: 'Ask for a review',
  tplQuick: 'Quick reply',
  resetTemplate: 'Reset to default',
  tplPreviewTitle: 'Preview',
  secDefaults: 'Defaults',
  adminLangDefault: 'Admin language',
  timezoneLabel: 'Studio time zone',
  currencyLabel: 'Currency',
  secData: 'Data',
  exportBookings: 'Export bookings (CSV)',
  exportReviews: 'Export reviews (CSV)',
  exportMessages: 'Export messages (CSV)',
  openTrash: 'Open Trash',
  trashRetentionNote: 'Deleted items stay in the trash for {n} days before they’re removed for good.',
  settingsSavedToast: 'Settings saved',
  invalidNumber: 'Enter a whole number of {min} or more.',
  // ---- domain
  domainStatus: 'Status',
  domainLive: 'Live over HTTPS',
  domainNotReachable: 'Not reachable over HTTPS',
  domainChecking: 'Checking…',
  domainCheckAgain: 'Check again',
  domainLastChecked: 'Checked {when}',
  domainNeverChecked: 'Not checked yet',
  domainWwwRedirect: 'www redirects correctly',
  domainWwwProblem: 'www isn’t redirecting',
  domainDns: 'DNS records',
  domainDnsHint: 'The records this domain needs to point at the website host. They’re set where the domain is registered (Wix), not here.',
  dnsType: 'Type',
  dnsHost: 'Host',
  dnsExpected: 'Should be',
  dnsFound: 'Currently',
  dnsOk: 'Correct',
  dnsMismatch: 'Different',
  dnsMissing: 'Missing',
  dnsUnknown: 'Couldn’t look up',
  sslLabel: 'SSL certificate',
  sslOk: 'Valid — renewed automatically by the host',
  sslUnknown: 'Not verified yet',
  domainRenewalReminder: 'Renewal reminder',
  domainEdit: 'Edit reminder',
  domainAddYear: '+1 year',
  domainCheckFailed: 'Couldn’t run the check',
  // ---- trash
  trashIntro: 'Deleted items stay here for {n} days, then they’re removed for good.',
  trashEmptyTitle: 'Trash is empty',
  trashEmptyBody: 'Deleted bookings, reviews, messages and services show up here and can be restored.',
  restore: 'Restore',
  deleteForever: 'Delete forever',
  emptyTrash: 'Empty trash',
  emptyTrashConfirm: 'Permanently delete everything in the trash? This can’t be undone.',
  deleteForeverConfirm: 'Permanently delete this item? This can’t be undone.',
  purgesIn: 'Removed in {n} days',
  purgesSoon: 'Removed at the next cleanup',
  kindBooking: 'Booking',
  kindReview: 'Review',
  kindMessage: 'Message',
  kindService: 'Service',
  deletedForeverToast: 'Deleted permanently',
  deletedOn: 'Deleted {when}',
  runCleanupNow: 'Run cleanup now',
  cleanupDone: 'Cleanup done: {purged} removed, {archived} archived',
  trashEmpty: 'Trash is empty',
  showTrash: 'Trash',
  newRequestsHint: '{n} new',
  markAllRead: 'Mark all read',
  expiredHint: 'The preferred time has passed.',
  followUpHint: 'Ask if they’d like a new time.',
  contactedHint: 'You’ve reached out. Waiting on the client.',
  perPage: 'per page',
  loadMore: 'Load more',
  csvExported: 'CSV downloaded',
  bookingUnnamed: 'No name given',
  lang_en: 'English',
  lang_uk: 'Ukrainian',
  lang_es: 'Spanish',
  customTime: 'Custom time',
  selectMode: 'Select',
  cancelSelect: 'Cancel selection',
  timezoneNote: 'Times shown in {tz}',
  weekOf: 'Week of {date}',
  submissionsList: 'All submissions',
  submittedAgo: 'Submitted {when}',
  noBookingsInRange: 'No requests in this range',
  openInCalendar: 'Open in calendar',
  sendConfirmation: 'Send confirmation',
  timeForAppointment: 'Appointment time',
  unknownService: 'Not specified',
  clientLangHint: 'Messages use the language the client used on the site.',
  nothingToShow: 'Nothing to show',
  // ── Dashboard ───────────────────────────────────────────────────────
  dashTitle: 'Dashboard',
  dashIntro: 'What needs you today.',
  dashToday: 'Today',
  dashTomorrow: 'Tomorrow',
  dashNoAppointments: 'No confirmed appointments',
  dashNeedsReply: 'Needs your reply',
  dashViewAll: 'View all',
  dashReviewsPending: 'Reviews waiting for moderation',
  dashNoPendingReviews: 'No reviews waiting',
  dashThisMonth: 'This month',
  statRequests: 'Requests',
  statConfirmed: 'Confirmed',
  statConversion: 'Conversion',
  statRevenue: 'Est. revenue',
  statTopServices: 'Most requested',
  revenueNote: 'Confirmed and completed appointments this month. Price ranges use the midpoint.',
  quickActions: 'Quick actions',
  qaViewWebsite: 'View website',
  qaAddPhoto: 'Add gallery photo',
  qaBlockTime: 'Block off time',
  blockTitle: 'Block off time',
  blockHint: 'Clients won’t be offered these times on the website.',
  blockDate: 'Date',
  blockAllDay: 'All day (closed)',
  blockFrom: 'From',
  blockTo: 'To',
  blockLabel: 'Label (optional)',
  blockSaved: 'Time blocked',
  blockInvalid: 'End time must be after start time.',
  moderate: 'Moderate',

  // ── Reviews ─────────────────────────────────────────────────────────
  reviewsTitle: 'Reviews',
  reviewsIntro: 'Moderate, reply and pick what shows on the homepage.',
  segPending: 'Pending',
  segPublished: 'Published',
  segHidden: 'Hidden',
  avgRating: 'Average rating',
  totalReviews: '{n} reviews',
  filterRating: 'Rating',
  anyRating: 'Any rating',
  starsN: '{n} stars',
  sortOldest: 'Oldest',
  sortHighest: 'Highest rating',
  sortLowest: 'Lowest rating',
  statusPending: 'Pending',
  statusPublished: 'Published',
  statusHidden: 'Hidden',
  actPublish: 'Publish',
  actHide: 'Hide',
  actUnhide: 'Show again',
  actFeature: 'Feature on homepage',
  actUnfeature: 'Remove from homepage',
  featuredChip: 'Featured',
  featuredLimit: 'You can feature up to 6 reviews.',
  replyPublicly: 'Reply publicly',
  replyHint: 'Shown under the review on the website.',
  replyPlaceholderNew: 'Thank you so much…',
  replySaved: 'Reply published',
  matchedClient: 'Matched client',
  noMatchedClient: 'No matching client found',
  reviewService: 'Service',
  setService: 'Choose a service…',
  reviewPhotos: 'Photos',
  reviewDeleted: 'Review moved to Trash',
  emptyReviews: 'No reviews yet',
  emptyReviewsBody: 'Reviews from the website appear here.',
  emptyPendingReviews: 'Nothing to moderate ✦',
  emptyPendingReviewsBody: 'New reviews will wait here when approval is required.',
  reviewDate: 'Date',
  reviewName: 'Name',
  helpfulCount: '{n} helpful',
  moderationOn: 'New reviews wait for your approval.',
  moderationOff: 'New reviews publish automatically. Change this in Settings.',
  // ── Services ────────────────────────────────────────────────────────
  servicesTitle: 'Services',
  servicesIntro: 'What clients can book. Drag to reorder categories and services.',
  addService: 'Add service',
  editService: 'Edit service',
  newServiceTitle: 'New service',
  categoryLabel: 'Category',
  categoryNew: 'New category…',
  categoryNamePlaceholder: 'e.g. Facials',
  categoryDescription: 'Category description',
  editCategory: 'Edit category',
  langEn: 'English',
  langUk: 'Ukrainian',
  fieldName: 'Name',
  fieldDescription: 'Description',
  fieldNote: 'Note (shown under the description)',
  fieldPrice: 'Price',
  priceHint: 'Fixed “$120” or a range “$140–160”.',
  fieldDuration: 'Duration',
  fieldBuffer: 'Buffer after',
  bufferHint: 'Cleanup time before the next appointment. Blank uses the default from Settings.',
  minutesUnit: 'minutes',
  activeLabel: 'Active',
  activeHint: 'Shown on the website.',
  bookableLabel: 'Bookable online',
  bookableHint: 'Offered in the booking form.',
  linkedBrands: 'Brands used',
  noBrandsYet: 'Add brands in the Brands tab first.',
  prepNotes: 'Prep notes',
  aftercareNotes: 'Aftercare notes',
  contraindications: 'Contraindications',
  careNotesHint: 'Shown on the service card so clients know what to expect.',
  duplicate: 'Duplicate',
  archive: 'Archive',
  unarchive: 'Restore',
  archivedChip: 'Archived',
  inactiveChip: 'Hidden',
  notBookableChip: 'Not bookable',
  uaMissing: 'UA missing',
  servicePreview: 'Website preview',
  serviceArchivedToast: 'Archived — bookings reference this service, so it was kept.',
  serviceDeletedToast: 'Service moved to Trash',
  serviceSaved: 'Service saved',
  servicesCount: '{n} services',
  reorderSaved: 'Order saved',
  emptyServices: 'No services yet',
  emptyServicesBody: 'Add your first service to show it on the website.',
  nameRequired: 'Name and price are required.',
  showArchived: 'Show archived',

  // ── Bio ─────────────────────────────────────────────────────────────
  bioTitle: 'Bio',
  bioIntro: 'Your story on the website, in English and Ukrainian.',
  bioHeadline: 'Headline',
  bioHeadlineHint: 'A short line under your name, e.g. “Licensed esthetician · 5+ years”.',
  bioEyebrow: 'Small label above the name',
  bioName: 'Name',
  bioStory: 'Story',
  bioParagraph: 'Paragraph {n}',
  bioYears: 'Years of experience',
  bioCertifications: 'Certifications & licenses',
  bioAddCertification: 'Add certification',
  bioCertTitle: 'Title',
  bioCertImage: 'Image (optional)',
  bioSpecialties: 'Specialties',
  bioSpecialtiesHint: 'Comma-separated, e.g. Acne, Peels, Anti-aging',
  bioBadges: 'Badges',
  bioBadgesHint: 'Comma-separated chips shown under the story.',
  bioPhoto: 'Profile photo',
  bioPublish: 'Publish',
  bioPublished: 'Published ✦',
  bioDraftSaved: 'Draft saved',
  bioUnpublished: 'Unpublished changes',
  bioUpToDate: 'Everything is published',
  bioMissingUk: 'Missing in Ukrainian',
  bioMissingEn: 'Missing in English',
  bioDiscardDraft: 'Discard draft',
  bioLastPublished: 'Last published {when}',
  bioNeverPublished: 'Not published yet',
  bioPreviewLang: 'Preview',

  // ── Gallery ─────────────────────────────────────────────────────────
  galleryTitle: 'Gallery',
  galleryIntro2: 'Photos for “The Experience” section. Drag to reorder; the cover shows first.',
  uploadPhotos: 'Upload photos',
  uploadingN: 'Uploading {done} of {total}…',
  uploadFailed: 'Upload failed',
  photosAdded: '{n} photos added',
  setCover: 'Set as cover',
  coverChip: 'Cover',
  hiddenChip: 'Hidden',
  hidePhoto: 'Hide',
  showPhoto: 'Show',
  editPhoto: 'Edit photo',
  altText: 'Alt text',
  altHint: 'Describes the photo for screen readers and search engines.',
  tagsLabel: 'Services shown',
  consentClient: 'This photo shows a client',
  consentLabel: 'I have the client’s written consent to publish this photo',
  consentRequired: 'Consent is required before this photo can be shown on the website.',
  bulkHide: 'Hide',
  bulkShow: 'Show',
  bulkTag: 'Tag',
  photosDeleted: '{n} photos removed',
  beforeAfter: 'Before / after',
  afterPhotoHint: 'Add an “after” photo to show a comparison slider on the website.',
  galleryEmpty: 'No photos yet',
  galleryEmptyBody: 'Upload photos of your results and your space.',
  tagPhotos: 'Tag photos',
  dropOrTap: 'Drop photos here or tap to choose',
  movePhoto: 'Move',

  // ── Brands ──────────────────────────────────────────────────────────
  brandsTitle: 'Brands',
  brandsIntro2: 'Brands you work with. Link them to services so service cards can show them.',
  brandDescription: 'Short description',
  brandWebsite: 'Website',
  brandHidden: 'Hidden from website',
  brandVisible: 'Shown on website',
  brandLinked: 'Used in {n} services',
  brandDeleted: 'Brand removed',
  brandNameRequired: 'Give the brand a name.',

  // ── Contact & hours ─────────────────────────────────────────────────
  contactTitle: 'Contact & hours',
  contactIntro: 'Contact details, weekly hours and closures. These decide what clients can book.',
  contactDetails: 'Contact details',
  mapPreview: 'Map preview',
  mapHint: 'Based on the address above.',
  socialLinks: 'Social links',
  weeklyHours: 'Weekly hours',
  hoursHint: 'Split shifts are fine. The booking form only offers times inside these hours.',
  closedDay: 'Closed',
  openDay: 'Open',
  addShift: 'Add shift',
  removeShift: 'Remove shift',
  shiftStart: 'Start',
  shiftEnd: 'End',
  closures: 'Holidays & closures',
  closuresHint: 'Whole days clients can’t book.',
  addClosure: 'Add closure',
  closureFrom: 'From',
  closureTo: 'To (optional)',
  closureLabel: 'Label',
  blockedTimesTitle: 'Blocked times',
  blockedTimesHint: 'Shorter windows blocked from the Dashboard.',
  contactMethodsTitle: 'How clients can ask to be contacted',
  contactMethodsHint: 'Offered as choices on the booking form.',
  needsPhone: 'Needs a phone number above',
  needsInstagram: 'Needs an Instagram link',
  needsEmail: 'Needs an email above',
  facebook: 'Facebook',
  whatsapp: 'WhatsApp',
  telegram: 'Telegram',
  hoursInvalid: 'Each shift must end after it starts.',
  contactSaved: 'Contact & hours saved',
  copyHoursToAll: 'Copy to all open days',

  // ── Messages ────────────────────────────────────────────────────────
  messagesTitle: 'Messages',
  messagesIntro: 'From the website’s contact form.',
  segInbox: 'Inbox',
  segReplied: 'Replied',
  msgNew: 'New',
  msgReplied: 'Replied',
  msgArchived: 'Archived',
  markReplied: 'Mark replied',
  replyByEmail: 'Reply by email',
  replyByText: 'Reply by text',
  messageDeleted: 'Message moved to Trash',
  emptyMessages: 'No messages',
  emptyMessagesBody: 'Messages from the contact form appear here.',
  messageFrom: 'From',
};

const uk: typeof en = {
  studioAdmin: 'Адмін студії',
  adminTitle: 'Адмін',
  navDashboard: 'Панель',
  navReviews: 'Відгуки',
  navServices: 'Послуги',
  navBio: 'Біо',
  navGallery: 'Галерея',
  navBrands: 'Бренди',
  navBookings: 'Записи',
  navMessages: 'Повідомлення',
  navContact: 'Контакти',
  navDomain: 'Домен',
  navSettings: 'Налаштування',
  navTrash: 'Кошик',
  navMore: 'Ще',
  groupOverview: 'Огляд',
  groupInbox: 'Вхідні',
  groupWebsite: 'Сайт',
  groupSetup: 'Налаштування',
  viewWebsite: 'Переглянути сайт',
  website: '← Сайт',
  account: 'Обліковий запис',
  signedInAs: 'Ви увійшли як',
  logout: 'Вийти',
  adminLanguage: 'Мова адмінки',
  dbUpdateTitle: 'Потрібне оновлення бази даних',
  dbUpdateBody:
    'Виконайте supabase/migrations/20260916_admin_redesign.sql у SQL-редакторі Supabase, щоб увімкнути статуси, нотатки, кошик і нові поля форми запису. До того цей екран працює в режимі сумісності.',

  loading: 'Завантаження…',
  retry: 'Повторити',
  errorTitle: 'Щось пішло не так',
  errorBody: 'Не вдалося завантажити. Перевірте з’єднання і спробуйте ще раз.',
  close: 'Закрити',
  back: 'Назад',
  done: 'Готово',
  undo: 'Скасувати дію',
  copy: 'Копіювати',
  copied: 'Скопійовано',
  search: 'Пошук',
  filters: 'Фільтри',
  clearFilters: 'Скинути фільтри',
  apply: 'Застосувати',
  select: 'Вибрати',
  selectAll: 'Вибрати всі',
  selectedCount: 'Вибрано: {n}',
  refresh: 'Оновити',
  saveChanges: 'Зберегти зміни',
  saved: 'Збережено',
  unsavedTitle: 'Незбережені зміни',
  unsavedBody: 'Є зміни, які ще не збережено. Усе одно вийти?',
  leave: 'Вийти',
  stay: 'Залишитись',
  toastSaved: '✓ Збережено',
  toastError: 'Не вдалося зберегти. Спробуйте ще раз.',
  toastUpdated: '✓ Оновлено',
  yes: 'Так',
  no: 'Ні',
  none: 'Немає',
  optional: 'Необов’язково',
  required: 'Обов’язково',
  showMore: 'Показати більше',
  showLess: 'Згорнути',
  today: 'Сьогодні',
  tomorrow: 'Завтра',
  yesterday: 'Вчора',
  noDate: 'Без дати',
  timeNotChosen: 'час не обрано',
  save: 'Зберегти',
  cancel: 'Скасувати',
  add: 'Додати',
  edit: 'Редагувати',
  delete: 'Видалити',
  replace: 'Замінити',
  remove: 'Прибрати',
  uploadImage: 'Завантажити фото',
  uploading: 'Завантаження…',
  livePreview: 'Попередній перегляд',
  weekdayShort: ['Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  weekdayLong: ['Неділя', 'Понеділок', 'Вівторок', 'Середа', 'Четвер', 'П’ятниця', 'Субота'],

  signIn: 'Вхід',
  signInSubtitle: 'Доступ лише для авторизованих',
  emailPlaceholder: 'Email',
  password: 'Пароль',
  passwordPlaceholder: 'Пароль',
  loginBtn: 'Увійти',
  signingIn: 'Вхід…',
  incorrectPassword: 'Невірний email або пароль',
  notAuthorized: 'Цей акаунт не має доступу до адмінпанелі.',
  checkingSession: 'Перевірка сесії…',

  bookingsTitle: 'Записи',
  bookingsIntro: 'Запити з кнопки «Записатися» на сайті.',
  viewInbox: 'Вхідні',
  viewCalendar: 'Календар',
  viewClients: 'Клієнти',
  segNeedsAction: 'Потребують дії',
  segConfirmed: 'Підтверджені',
  segPast: 'Минулі',
  segArchived: 'Архів',
  segAll: 'Усі',
  sortNeedsFirst: 'Спочатку ті, що потребують дії',
  sortNewest: 'Спочатку нові',
  sortLabel: 'Сортування',
  searchBookings: 'Пошук за ім’ям, телефоном, email або послугою',
  filterStatus: 'Статус',
  filterService: 'Послуга',
  filterFrom: 'Від',
  filterTo: 'До',
  filterAnyStatus: 'Будь-який статус',
  filterAnyService: 'Будь-яка послуга',
  filterDateRange: 'Бажана дата',
  statusNew: 'Новий',
  statusContacted: 'На зв’язку',
  statusConfirmed: 'Підтверджено',
  statusCompleted: 'Завершено',
  statusDeclined: 'Відхилено',
  statusCancelled: 'Скасовано',
  statusNoShow: 'Не прийшов',
  statusArchived: 'В архіві',
  badgeReplyToday: 'Відповісти сьогодні',
  badgeExpired: 'Прострочено',
  badgeConflict: 'Конфлікт часу',
  badgeReturning: 'Постійний · {n} візитів',
  badgeReturningRequests: 'Постійний · {n} запитів',
  badgeNewClient: 'Новий клієнт',
  badgeSubmissions: '×{n} заявок',
  badgeUnread: 'Непрочитано',
  badgeNoTime: 'Час не обрано',
  badgeOutsideHours: 'Поза робочими годинами',
  badgeClosedDay: 'Зачинено в цей день',
  summaryReplyToday: '{n} потребують відповіді сьогодні',
  summaryDuplicates: '{n} дублікатів об’єднано',
  summaryConflicts: '{n} конфліктів часу',
  summaryConfirmedWeek: '{n} підтверджено цього тижня',
  summaryAllClear: 'Усе оброблено ✦',
  preferred: 'Бажано',
  submitted: 'Надіслано',
  via: 'через',
  methodSms: 'SMS',
  methodInstagram: 'Instagram',
  methodEmail: 'Email',
  methodCall: 'Дзвінок',
  requestDetails: 'Запит',
  client: 'Клієнт',
  contact: 'Контакти',
  actionText: 'Написати',
  actionCall: 'Подзвонити',
  actionEmail: 'Email',
  noPhoneCaptured: 'Телефон не збережено (старий запит). Запитайте його у відповіді.',
  service: 'Послуга',
  price: 'Ціна',
  duration: 'Тривалість',
  minutesShort: '{n} хв',
  preferredTime: 'Бажаний час',
  alsoOk: 'Також підходить',
  optionsFromSubmissions: 'Час із {n} заявок',
  clientMessage: 'Повідомлення клієнта',
  siteLanguage: 'Мова сайту',
  clientHistory: 'Історія клієнта',
  requestsCount: 'Запитів: {n}',
  visitsCount: 'Візитів: {n}',
  upcomingCount: 'Майбутніх: {n}',
  lastService: 'Остання послуга',
  lastVisit: 'Останній візит',
  firstRequest: 'Перший запит',
  privateNotes: 'Приватні нотатки',
  notesPlaceholder: 'Бачите лише ви. Алергії, побажання, нагадування…',
  notesSaving: 'Збереження…',
  notesSaved: 'Збережено',
  activity: 'Активність',
  noActivity: 'Поки що нічого.',
  evCreated: 'Запит отримано',
  evResubmitted: 'Надіслано повторно',
  evStatus: '{from} → {to}',
  evContacted: 'Ви зв’язалися ({channel}: {kind})',
  evNote: 'Нотатка',
  evMerged: 'Об’єднано з іншим запитом',
  evMergedIn: 'Дублікати об’єднано в цей запит',
  evTrashed: 'Переміщено в кошик',
  evRestored: 'Відновлено з кошика',
  evRescheduled: 'Час змінено',
  actConfirm: 'Підтвердити',
  actSuggest: 'Запропонувати інший час',
  actDecline: 'Відхилити',
  actComplete: 'Позначити завершеним',
  actNoShow: 'Не прийшов',
  actArchive: 'В архів',
  actFollowUp: 'Нагадати про себе',
  actReopen: 'Відкрити знову',
  actCancelAppt: 'Скасувати запис',
  actMarkRead: 'Позначити прочитаним',
  actMarkUnread: 'Позначити непрочитаним',
  actDelete: 'Видалити',
  actRestore: 'Відновити',
  actDeleteForever: 'Видалити назавжди',
  actReminder: 'Надіслати нагадування',
  actRequestReview: 'Попросити відгук',
  actMore: 'Більше дій',
  actExportCsv: 'Експорт CSV',
  actDownloadIcs: 'Додати в календар (.ics)',
  actAi: 'AI-помічник',
  confirmTitle: 'Підтвердити запис',
  confirmFor: 'Підтвердити на',
  confirmAndText: 'Підтвердити й написати',
  confirmAndEmail: 'Підтвердити й надіслати email',
  confirmOnly: 'Підтвердити без повідомлення',
  chooseTime: 'Оберіть час',
  anotherTime: 'Інший час…',
  suggestTitle: 'Запропонувати інший час',
  suggestHint: 'Оберіть до 3 вільних слотів, щоб запропонувати клієнту.',
  nextOpen: 'Найближчі вільні слоти',
  noOpenSlots: 'Немає вільних слотів найближчими тижнями. Змініть години в «Контактах».',
  openMessages: 'Відкрити Повідомлення',
  openEmail: 'Відкрити пошту',
  openInstagram: 'Відкрити Instagram',
  messagePreview: 'Повідомлення',
  editMessage: 'Відредагуйте перед надсиланням — нічого не надсилається автоматично.',
  declineTitle: 'Відхилити запит',
  declineHint: 'Клієнт отримає ваше повідомлення; запит перейде у «Відхилено».',
  deleteTitle: 'Видалити запит?',
  deleteBody: 'Він переміститься в кошик на 30 днів, після чого зникне.',
  deletedToast: 'Переміщено в кошик',
  restoredToast: 'Відновлено',
  purgeTitle: 'Видалити назавжди?',
  purgeBody: 'Цю дію неможливо скасувати.',
  conflictConfirmed: 'Перетинається з підтвердженим записом: {name}',
  conflictPending: 'Перетинається із запитом від {name}',
  conflictOutside: 'Поза робочими годинами',
  conflictBlackout: 'Припадає на вихідний день',
  conflictBlocked: 'Перетинається із заблокованим часом',
  duplicatesTitle: 'Заявки',
  duplicatesHint: 'Клієнт надіслав це {n} рази. Показано одну картку; нічого не видалено.',
  aiSummary: 'Стисло',
  aiDraft: 'Чернетка відповіді',
  aiGenerate: 'Створити чернетку з AI',
  aiWorking: 'Думаю…',
  aiUseDraft: 'Використати чернетку',
  bulkMarkRead: 'Прочитано',
  bulkArchive: 'В архів',
  bulkDelete: 'Видалити',
  calDay: 'День',
  calWeek: 'Тиждень',
  calToday: 'Сьогодні',
  calPrev: 'Назад',
  calNext: 'Далі',
  calPending: 'Очікує',
  calConfirmed: 'Підтверджено',
  calBlocked: 'Заблоковано',
  calClosed: 'Зачинено',
  calNothing: 'Нічого не заплановано',
  calBlockTime: 'Заблокувати час',
  clientsSearch: 'Пошук клієнтів',
  clientRequests: 'Запити',
  clientVisits: 'Візити',
  clientUpcoming: 'Майбутні',
  clientNone: 'Клієнтів поки немає',
  clientNoneBody: 'Клієнти з’являться тут після перших запитів на запис.',
  clientSince: 'Клієнт з',
  emptyInboxTitle: 'Вхідні порожні ✦',
  emptyInboxBody: 'Нові запити з сайту з’являтимуться тут.',
  emptySegment: 'Тут нічого немає',
  emptySegmentBody: 'Запити потрапляють сюди зі зміною статусу.',
  emptySearch: 'Нічого не знайдено за запитом «{q}»',
  emptySearchBody: 'Спробуйте ім’я, номер телефону, email або послугу.',
  trashTitle: 'Кошик',
  // ---- settings
  settingsTitle: 'Налаштування',
  settingsIntro: 'Акаунт, правила запису, сповіщення та шаблони відповідей.',
  secAccount: 'Акаунт',
  changePassword: 'Змінити пароль',
  newPassword: 'Новий пароль',
  confirmPassword: 'Повторіть новий пароль',
  passwordMismatch: 'Паролі не збігаються.',
  passwordTooShort: 'Щонайменше 8 символів.',
  passwordUpdated: 'Пароль оновлено',
  updatePassword: 'Оновити пароль',
  twoFactor: 'Двофакторна автентифікація',
  twoFactorOnHint: 'Увімкнено — для входу потрібен код із застосунку-автентифікатора.',
  twoFactorOffHint: 'Вимкнено — адмінку захищає лише пароль.',
  twoFactorEnable: 'Налаштувати 2FA',
  twoFactorDisable: 'Вимкнути 2FA',
  twoFactorScan: 'Відскануйте QR-код у застосунку-автентифікаторі (Google Authenticator, 1Password, Authy) і введіть 6-значний код.',
  twoFactorSecret: 'Або введіть цей ключ у застосунок вручну',
  twoFactorCode: 'Код із застосунку',
  twoFactorVerify: 'Перевірити й увімкнути',
  twoFactorInvalid: 'Код не підійшов. Дочекайтеся наступного і спробуйте ще раз.',
  twoFactorWarning: 'Бережіть автентифікатор: без нього ви не зможете увійти. Якщо він втрачений, фактор можна видалити в панелі Supabase (Authentication → Users).',
  twoFactorDisableConfirm: 'Вимкнути двофакторну автентифікацію? Для входу буде потрібен лише пароль.',
  mfaTitle: 'Код двофакторної автентифікації',
  mfaBody: 'Введіть 6-значний код із застосунку-автентифікатора.',
  mfaSubmit: 'Перевірити',
  sessions: 'Сеанси',
  signOutOthers: 'Вийти на інших пристроях',
  signOutOthersHint: 'Завершує всі сеанси, крім цього.',
  signedOutOthers: 'Інші пристрої вийшли з акаунта',
  secBookingRules: 'Правила запису',
  minNotice: 'Мінімальний запас часу (годин)',
  minNoticeHint: 'Клієнти не зможуть обрати час раніше, ніж через цей проміжок.',
  maxDaysAhead: 'Запис максимум на (днів наперед)',
  slotMinutes: 'Крок часу (хвилин)',
  defaultBuffer: 'Стандартна перерва між записами (хвилин)',
  defaultBufferHint: 'Використовується, якщо у послуги немає власної перерви.',
  autoArchiveDays: 'Автоархівація завершених запитів через (днів)',
  autoArchiveHint: 'Виконані, відхилені, скасовані запити та неявки переходять до архіву. 0 вимикає.',
  trashRetention: 'Зберігати кошик (днів)',
  reviewsNeedApproval: 'Відгуки потребують схвалення перед показом на сайті',
  secNotifications: 'Сповіщення',
  notifyNewBooking: 'Надсилати email про кожен новий запит на запис',
  notifyNewReview: 'Надсилати email про кожен новий відгук',
  notifyNewMessage: 'Надсилати email про кожне нове повідомлення',
  notifyEmail: 'Надсилати сповіщення на',
  notifyEmailHint: 'Залиште порожнім, щоб використовувати email студії з розділу «Контакти».',
  notifyNotConfigured: 'Надсилання email ще не налаштовано (RESEND_API_KEY). Сповіщення запрацюють після налаштування.',
  notifyConfigured: 'Надсилання email налаштовано.',
  secTemplates: 'Шаблони відповідей',
  templatesHint: 'Використовуються кнопками «Підтвердити», «Запропонувати час», «Відхилити», «Нагадування» та «Попросити відгук». Натисніть на змінну, щоб вставити її в місце курсора.',
  tplConfirm: 'Підтвердження',
  tplSuggest: 'Запропонувати час',
  tplDecline: 'Відхилення',
  tplReminder: 'Нагадування',
  tplReview: 'Прохання про відгук',
  tplQuick: 'Швидка відповідь',
  resetTemplate: 'Повернути стандартний',
  tplPreviewTitle: 'Попередній перегляд',
  secDefaults: 'Стандартні значення',
  adminLangDefault: 'Мова адмінки',
  timezoneLabel: 'Часовий пояс студії',
  currencyLabel: 'Валюта',
  secData: 'Дані',
  exportBookings: 'Експортувати записи (CSV)',
  exportReviews: 'Експортувати відгуки (CSV)',
  exportMessages: 'Експортувати повідомлення (CSV)',
  openTrash: 'Відкрити кошик',
  trashRetentionNote: 'Видалені елементи зберігаються в кошику {n} днів, а потім видаляються назавжди.',
  settingsSavedToast: 'Налаштування збережено',
  invalidNumber: 'Введіть ціле число від {min}.',
  // ---- domain
  domainStatus: 'Статус',
  domainLive: 'Працює через HTTPS',
  domainNotReachable: 'Недоступний через HTTPS',
  domainChecking: 'Перевіряємо…',
  domainCheckAgain: 'Перевірити знову',
  domainLastChecked: 'Перевірено {when}',
  domainNeverChecked: 'Ще не перевірялося',
  domainWwwRedirect: 'www перенаправляє правильно',
  domainWwwProblem: 'www не перенаправляє',
  domainDns: 'DNS-записи',
  domainDnsHint: 'Записи, на які має вказувати домен, щоб сайт працював. Їх змінюють там, де зареєстровано домен (Wix), а не тут.',
  dnsType: 'Тип',
  dnsHost: 'Хост',
  dnsExpected: 'Має бути',
  dnsFound: 'Зараз',
  dnsOk: 'Правильно',
  dnsMismatch: 'Відрізняється',
  dnsMissing: 'Відсутній',
  dnsUnknown: 'Не вдалося перевірити',
  sslLabel: 'SSL-сертифікат',
  sslOk: 'Дійсний — хостинг поновлює автоматично',
  sslUnknown: 'Ще не перевірено',
  domainRenewalReminder: 'Нагадування про поновлення',
  domainEdit: 'Змінити нагадування',
  domainAddYear: '+1 рік',
  domainCheckFailed: 'Не вдалося виконати перевірку',
  // ---- trash
  trashIntro: 'Видалені елементи зберігаються тут {n} днів, а потім видаляються назавжди.',
  trashEmptyTitle: 'Кошик порожній',
  trashEmptyBody: 'Видалені записи, відгуки, повідомлення та послуги з’являються тут і їх можна відновити.',
  restore: 'Відновити',
  deleteForever: 'Видалити назавжди',
  emptyTrash: 'Очистити кошик',
  emptyTrashConfirm: 'Назавжди видалити все з кошика? Цю дію не можна скасувати.',
  deleteForeverConfirm: 'Назавжди видалити цей елемент? Цю дію не можна скасувати.',
  purgesIn: 'Буде видалено через {n} дн.',
  purgesSoon: 'Буде видалено під час наступного очищення',
  kindBooking: 'Запис',
  kindReview: 'Відгук',
  kindMessage: 'Повідомлення',
  kindService: 'Послуга',
  deletedForeverToast: 'Видалено назавжди',
  deletedOn: 'Видалено {when}',
  runCleanupNow: 'Запустити очищення',
  cleanupDone: 'Очищення виконано: видалено {purged}, заархівовано {archived}',
  trashEmpty: 'Кошик порожній',
  showTrash: 'Кошик',
  newRequestsHint: 'нових: {n}',
  markAllRead: 'Позначити всі прочитаними',
  expiredHint: 'Бажаний час уже минув.',
  followUpHint: 'Запитайте, чи підійде інший час.',
  contactedHint: 'Ви зв’язалися. Чекаємо на клієнта.',
  perPage: 'на сторінці',
  loadMore: 'Показати ще',
  csvExported: 'CSV завантажено',
  bookingUnnamed: 'Без імені',
  lang_en: 'Англійська',
  lang_uk: 'Українська',
  lang_es: 'Іспанська',
  customTime: 'Інший час',
  selectMode: 'Вибрати',
  cancelSelect: 'Скасувати вибір',
  timezoneNote: 'Час показано для {tz}',
  weekOf: 'Тиждень від {date}',
  submissionsList: 'Усі заявки',
  submittedAgo: 'Надіслано {when}',
  noBookingsInRange: 'Немає запитів у цьому діапазоні',
  openInCalendar: 'Відкрити в календарі',
  sendConfirmation: 'Надіслати підтвердження',
  timeForAppointment: 'Час запису',
  unknownService: 'Не вказано',
  clientLangHint: 'Повідомлення складаються мовою, якою клієнт користувався на сайті.',
  nothingToShow: 'Нічого показувати',
  dashTitle: 'Панель',
  dashIntro: 'Що потребує вашої уваги сьогодні.',
  dashToday: 'Сьогодні',
  dashTomorrow: 'Завтра',
  dashNoAppointments: 'Немає підтверджених записів',
  dashNeedsReply: 'Потребують відповіді',
  dashViewAll: 'Переглянути всі',
  dashReviewsPending: 'Відгуки на модерації',
  dashNoPendingReviews: 'Немає відгуків на модерації',
  dashThisMonth: 'Цього місяця',
  statRequests: 'Запитів',
  statConfirmed: 'Підтверджено',
  statConversion: 'Конверсія',
  statRevenue: 'Орієнтовний дохід',
  statTopServices: 'Найпопулярніші',
  revenueNote: 'Підтверджені та завершені записи цього місяця. Для діапазонів цін береться середина.',
  quickActions: 'Швидкі дії',
  qaViewWebsite: 'Переглянути сайт',
  qaAddPhoto: 'Додати фото в галерею',
  qaBlockTime: 'Заблокувати час',
  blockTitle: 'Заблокувати час',
  blockHint: 'Клієнтам не пропонуватимуть цей час на сайті.',
  blockDate: 'Дата',
  blockAllDay: 'Увесь день (зачинено)',
  blockFrom: 'З',
  blockTo: 'До',
  blockLabel: 'Підпис (необов’язково)',
  blockSaved: 'Час заблоковано',
  blockInvalid: 'Час завершення має бути пізніше початку.',
  moderate: 'Модерувати',

  reviewsTitle: 'Відгуки',
  reviewsIntro: 'Модеруйте, відповідайте та обирайте, що показувати на головній.',
  segPending: 'Очікують',
  segPublished: 'Опубліковані',
  segHidden: 'Приховані',
  avgRating: 'Середня оцінка',
  totalReviews: 'Відгуків: {n}',
  filterRating: 'Оцінка',
  anyRating: 'Будь-яка оцінка',
  starsN: '{n} зірок',
  sortOldest: 'Спочатку старі',
  sortHighest: 'Найвища оцінка',
  sortLowest: 'Найнижча оцінка',
  statusPending: 'Очікує',
  statusPublished: 'Опубліковано',
  statusHidden: 'Приховано',
  actPublish: 'Опублікувати',
  actHide: 'Приховати',
  actUnhide: 'Показати знову',
  actFeature: 'Показати на головній',
  actUnfeature: 'Прибрати з головної',
  featuredChip: 'На головній',
  featuredLimit: 'Можна виділити до 6 відгуків.',
  replyPublicly: 'Відповісти публічно',
  replyHint: 'Показується під відгуком на сайті.',
  replyPlaceholderNew: 'Дуже дякую…',
  replySaved: 'Відповідь опубліковано',
  matchedClient: 'Знайдений клієнт',
  noMatchedClient: 'Відповідного клієнта не знайдено',
  reviewService: 'Послуга',
  setService: 'Оберіть послугу…',
  reviewPhotos: 'Фото',
  reviewDeleted: 'Відгук переміщено в кошик',
  emptyReviews: 'Відгуків поки немає',
  emptyReviewsBody: 'Відгуки з сайту з’являтимуться тут.',
  emptyPendingReviews: 'Нічого модерувати ✦',
  emptyPendingReviewsBody: 'Нові відгуки чекатимуть тут, якщо потрібне схвалення.',
  reviewDate: 'Дата',
  reviewName: 'Ім’я',
  helpfulCount: 'Корисно: {n}',
  moderationOn: 'Нові відгуки чекають на ваше схвалення.',
  moderationOff: 'Нові відгуки публікуються автоматично. Змінити можна в Налаштуваннях.',
  servicesTitle: 'Послуги',
  servicesIntro: 'Що можуть замовити клієнти. Перетягуйте, щоб змінити порядок категорій і послуг.',
  addService: 'Додати послугу',
  editService: 'Редагувати послугу',
  newServiceTitle: 'Нова послуга',
  categoryLabel: 'Категорія',
  categoryNew: 'Нова категорія…',
  categoryNamePlaceholder: 'напр. Догляд за обличчям',
  categoryDescription: 'Опис категорії',
  editCategory: 'Редагувати категорію',
  langEn: 'Англійська',
  langUk: 'Українська',
  fieldName: 'Назва',
  fieldDescription: 'Опис',
  fieldNote: 'Примітка (під описом)',
  fieldPrice: 'Ціна',
  priceHint: 'Фіксована «$120» або діапазон «$140–160».',
  fieldDuration: 'Тривалість',
  fieldBuffer: 'Перерва після',
  bufferHint: 'Час на прибирання перед наступним записом. Порожнє — стандартне з Налаштувань.',
  minutesUnit: 'хвилин',
  activeLabel: 'Активна',
  activeHint: 'Показується на сайті.',
  bookableLabel: 'Онлайн-запис',
  bookableHint: 'Пропонується у формі запису.',
  linkedBrands: 'Бренди, що використовуються',
  noBrandsYet: 'Спершу додайте бренди у вкладці «Бренди».',
  prepNotes: 'Підготовка',
  aftercareNotes: 'Догляд після',
  contraindications: 'Протипоказання',
  careNotesHint: 'Показується на картці послуги, щоб клієнти знали, чого очікувати.',
  duplicate: 'Дублювати',
  archive: 'В архів',
  unarchive: 'Відновити',
  archivedChip: 'В архіві',
  inactiveChip: 'Приховано',
  notBookableChip: 'Без онлайн-запису',
  uaMissing: 'Немає UA',
  servicePreview: 'Як на сайті',
  serviceArchivedToast: 'Заархівовано — на цю послугу є записи, тому її збережено.',
  serviceDeletedToast: 'Послугу переміщено в кошик',
  serviceSaved: 'Послугу збережено',
  servicesCount: 'Послуг: {n}',
  reorderSaved: 'Порядок збережено',
  emptyServices: 'Послуг поки немає',
  emptyServicesBody: 'Додайте першу послугу, щоб показати її на сайті.',
  nameRequired: 'Назва та ціна обов’язкові.',
  showArchived: 'Показати архів',

  bioTitle: 'Біо',
  bioIntro: 'Ваша історія на сайті англійською та українською.',
  bioHeadline: 'Заголовок',
  bioHeadlineHint: 'Короткий рядок під ім’ям, напр. «Ліцензований естетист · 5+ років».',
  bioEyebrow: 'Маленький підпис над ім’ям',
  bioName: 'Ім’я',
  bioStory: 'Історія',
  bioParagraph: 'Абзац {n}',
  bioYears: 'Років досвіду',
  bioCertifications: 'Сертифікати та ліцензії',
  bioAddCertification: 'Додати сертифікат',
  bioCertTitle: 'Назва',
  bioCertImage: 'Зображення (необов’язково)',
  bioSpecialties: 'Спеціалізації',
  bioSpecialtiesHint: 'Через кому, напр. Акне, Пілінги, Анти-ейдж',
  bioBadges: 'Бейджі',
  bioBadgesHint: 'Через кому; показуються під історією.',
  bioPhoto: 'Фото профілю',
  bioPublish: 'Опублікувати',
  bioPublished: 'Опубліковано ✦',
  bioDraftSaved: 'Чернетку збережено',
  bioUnpublished: 'Є неопубліковані зміни',
  bioUpToDate: 'Усе опубліковано',
  bioMissingUk: 'Немає української',
  bioMissingEn: 'Немає англійської',
  bioDiscardDraft: 'Відхилити чернетку',
  bioLastPublished: 'Опубліковано {when}',
  bioNeverPublished: 'Ще не опубліковано',
  bioPreviewLang: 'Перегляд',

  galleryTitle: 'Галерея',
  galleryIntro2: 'Фото для розділу «Досвід». Перетягуйте, щоб змінити порядок; обкладинка показується першою.',
  uploadPhotos: 'Завантажити фото',
  uploadingN: 'Завантаження {done} з {total}…',
  uploadFailed: 'Не вдалося завантажити',
  photosAdded: 'Додано фото: {n}',
  setCover: 'Зробити обкладинкою',
  coverChip: 'Обкладинка',
  hiddenChip: 'Приховано',
  hidePhoto: 'Приховати',
  showPhoto: 'Показати',
  editPhoto: 'Редагувати фото',
  altText: 'Alt-текст',
  altHint: 'Опис фото для програм читання з екрана та пошуку.',
  tagsLabel: 'Послуги на фото',
  consentClient: 'На фото клієнт',
  consentLabel: 'Я маю письмову згоду клієнта на публікацію цього фото',
  consentRequired: 'Без згоди фото не показується на сайті.',
  bulkHide: 'Приховати',
  bulkShow: 'Показати',
  bulkTag: 'Теги',
  photosDeleted: 'Видалено фото: {n}',
  beforeAfter: 'До / після',
  afterPhotoHint: 'Додайте фото «після», щоб показати повзунок порівняння на сайті.',
  galleryEmpty: 'Фото поки немає',
  galleryEmptyBody: 'Завантажте фото результатів і вашого простору.',
  tagPhotos: 'Теги для фото',
  dropOrTap: 'Перетягніть фото сюди або торкніться, щоб вибрати',
  movePhoto: 'Перемістити',

  brandsTitle: 'Бренди',
  brandsIntro2: 'Бренди, з якими ви працюєте. Прив’яжіть їх до послуг, щоб показувати на картках.',
  brandDescription: 'Короткий опис',
  brandWebsite: 'Сайт',
  brandHidden: 'Приховано з сайту',
  brandVisible: 'Показується на сайті',
  brandLinked: 'Використовується у {n} послугах',
  brandDeleted: 'Бренд видалено',
  brandNameRequired: 'Вкажіть назву бренду.',

  contactTitle: 'Контакти та години',
  contactIntro: 'Контактні дані, робочі години та вихідні. Від них залежить, що можуть обрати клієнти.',
  contactDetails: 'Контактні дані',
  mapPreview: 'Карта',
  mapHint: 'За адресою вище.',
  socialLinks: 'Соцмережі',
  weeklyHours: 'Робочі години',
  hoursHint: 'Можна кілька змін на день. Форма запису пропонує лише час у ці години.',
  closedDay: 'Зачинено',
  openDay: 'Відчинено',
  addShift: 'Додати зміну',
  removeShift: 'Прибрати зміну',
  shiftStart: 'Початок',
  shiftEnd: 'Кінець',
  closures: 'Свята та вихідні',
  closuresHint: 'Цілі дні, коли запис недоступний.',
  addClosure: 'Додати вихідний',
  closureFrom: 'З',
  closureTo: 'До (необов’язково)',
  closureLabel: 'Підпис',
  blockedTimesTitle: 'Заблокований час',
  blockedTimesHint: 'Коротші проміжки, заблоковані з Панелі.',
  contactMethodsTitle: 'Як клієнти можуть попросити зв’язатися',
  contactMethodsHint: 'Пропонуються як варіанти у формі запису.',
  needsPhone: 'Потрібен номер телефону вище',
  needsInstagram: 'Потрібне посилання на Instagram',
  needsEmail: 'Потрібен email вище',
  facebook: 'Facebook',
  whatsapp: 'WhatsApp',
  telegram: 'Telegram',
  hoursInvalid: 'Кожна зміна має закінчуватися пізніше, ніж починається.',
  contactSaved: 'Контакти та години збережено',
  copyHoursToAll: 'Скопіювати на всі робочі дні',

  messagesTitle: 'Повідомлення',
  messagesIntro: 'З контактної форми на сайті.',
  segInbox: 'Вхідні',
  segReplied: 'З відповіддю',
  msgNew: 'Нове',
  msgReplied: 'Відповідь надано',
  msgArchived: 'В архіві',
  markReplied: 'Позначити як відповіли',
  replyByEmail: 'Відповісти на email',
  replyByText: 'Відповісти SMS',
  messageDeleted: 'Повідомлення переміщено в кошик',
  emptyMessages: 'Повідомлень немає',
  emptyMessagesBody: 'Повідомлення з контактної форми з’являтимуться тут.',
  messageFrom: 'Від',
};

export const ADMIN_DICT = { en, uk };
export type AdminDict = typeof en;
