// Admin UI strings. Every key exists in both EN and UK — TypeScript enforces
// that `uk` has at least every key `en` has (see AdminLang.tsx).
// Placeholders like {n} / {name} are filled with `fmt()` from AdminLang.

const en = {
  // ── Shell / navigation ──────────────────────────────────────────────
  studioAdmin: 'Studio Admin',
  adminTitle: 'Admin',
  navDashboard: 'Dashboard',
  navReviews: 'Reviews',
  navServices: 'Services',
  navBio: 'Bio',
  navGallery: 'Gallery',
  navBrands: 'Brands',
  navBookings: 'Bookings',
  navMessages: 'Messages',
  navContact: 'Contact',
  navDomain: 'Domain',
  navSettings: 'Settings',
  navTrash: 'Trash',
  navMore: 'More',
  groupOverview: 'Overview',
  groupInbox: 'Inbox',
  groupWebsite: 'Website',
  groupSetup: 'Setup',
  viewWebsite: 'View website',
  website: '← Website',
  account: 'Account',
  signedInAs: 'Signed in as',
  logout: 'Log out',
  adminLanguage: 'Admin language',
  dbUpdateTitle: 'Database update needed',
  dbUpdateBody:
    'Run supabase/migrations/20260916_admin_redesign.sql in the Supabase SQL editor to enable statuses, notes, Trash and the new booking form fields. Until then this screen works in compatibility mode.',

  // ── Common UI ───────────────────────────────────────────────────────
  loading: 'Loading…',
  retry: 'Retry',
  errorTitle: 'Something went wrong',
  errorBody: 'We couldn’t load this. Check your connection and try again.',
  close: 'Close',
  back: 'Back',
  done: 'Done',
  undo: 'Undo',
  copy: 'Copy',
  copied: 'Copied',
  search: 'Search',
  filters: 'Filters',
  clearFilters: 'Clear filters',
  apply: 'Apply',
  select: 'Select',
  selectAll: 'Select all',
  selectedCount: '{n} selected',
  refresh: 'Refresh',
  saveChanges: 'Save changes',
  saved: 'Saved',
  unsavedTitle: 'Unsaved changes',
  unsavedBody: 'You have changes that haven’t been saved. Leave anyway?',
  leave: 'Leave',
  stay: 'Stay',
  toastSaved: '✓ Saved',
  toastError: 'Couldn’t save. Please try again.',
  toastUpdated: '✓ Updated',
  yes: 'Yes',
  no: 'No',
  none: 'None',
  optional: 'Optional',
  required: 'Required',
  showMore: 'Show more',
  showLess: 'Show less',
  today: 'Today',
  tomorrow: 'Tomorrow',
  yesterday: 'Yesterday',
  noDate: 'No date',
  timeNotChosen: 'time not chosen',
  save: 'Save',
  cancel: 'Cancel',
  add: 'Add',
  edit: 'Edit',
  delete: 'Delete',
  replace: 'Replace',
  remove: 'Remove',
  uploadImage: 'Upload image',
  uploading: 'Uploading…',
  livePreview: 'Live preview',
  weekdayShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  weekdayLong: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],

  // ── Auth ────────────────────────────────────────────────────────────
  signIn: 'Sign in',
  signInSubtitle: 'Authorized access only',
  emailPlaceholder: 'Email',
  password: 'Password',
  passwordPlaceholder: 'Password',
  loginBtn: 'Sign in',
  signingIn: 'Signing in…',
  incorrectPassword: 'Incorrect email or password',
  notAuthorized: 'This account is not authorized for admin access.',
  checkingSession: 'Checking session…',

  // ── Bookings ────────────────────────────────────────────────────────
  bookingsTitle: 'Bookings',
  bookingsIntro: 'Requests from the website’s Book button.',
  viewInbox: 'Inbox',
  viewCalendar: 'Calendar',
  viewClients: 'Clients',
  segNeedsAction: 'Needs action',
  segConfirmed: 'Confirmed',
  segPast: 'Past',
  segArchived: 'Archived',
  segAll: 'All',
  sortNeedsFirst: 'Needs action first',
  sortNewest: 'Newest submitted',
  sortLabel: 'Sort',
  searchBookings: 'Search name, phone, email or service',
  filterStatus: 'Status',
  filterService: 'Service',
  filterFrom: 'From',
  filterTo: 'To',
  filterAnyStatus: 'Any status',
  filterAnyService: 'Any service',
  filterDateRange: 'Preferred date',
  statusNew: 'New',
  statusContacted: 'Contacted',
  statusConfirmed: 'Confirmed',
  statusCompleted: 'Completed',
  statusDeclined: 'Declined',
  statusCancelled: 'Cancelled',
  statusNoShow: 'No-show',
  statusArchived: 'Archived',
  badgeReplyToday: 'Reply today',
  badgeExpired: 'Expired',
  badgeConflict: 'Time conflict',
  badgeReturning: 'Returning · {n} visits',
  badgeReturningRequests: 'Returning · {n} requests',
  badgeNewClient: 'New client',
  badgeSubmissions: '×{n} submissions',
  badgeUnread: 'Unread',
  badgeNoTime: 'No time chosen',
  badgeOutsideHours: 'Outside hours',
  badgeClosedDay: 'Closed that day',
  summaryReplyToday: '{n} need a reply today',
  summaryDuplicates: '{n} duplicates merged',
  summaryConflicts: '{n} time conflicts',
  summaryConfirmedWeek: '{n} confirmed this week',
  summaryAllClear: 'All caught up ✦',
  preferred: 'Preferred',
  submitted: 'Submitted',
  via: 'via',
  methodSms: 'Text',
  methodInstagram: 'Instagram',
  methodEmail: 'Email',
  methodCall: 'Call',
  requestDetails: 'Request',
  client: 'Client',
  contact: 'Contact',
  actionText: 'Text',
  actionCall: 'Call',
  actionEmail: 'Email',
  noPhoneCaptured: 'No phone captured (older request). Ask for it in your reply.',
  service: 'Service',
  price: 'Price',
  duration: 'Duration',
  minutesShort: '{n} min',
  preferredTime: 'Preferred time',
  alsoOk: 'Also OK',
  optionsFromSubmissions: 'Times from the {n} submissions',
  clientMessage: 'Client’s message',
  siteLanguage: 'Site language',
  clientHistory: 'Client history',
  requestsCount: '{n} requests',
  visitsCount: '{n} visits',
  upcomingCount: '{n} upcoming',
  lastService: 'Last service',
  lastVisit: 'Last visit',
  firstRequest: 'First request',
  privateNotes: 'Private notes',
  notesPlaceholder: 'Only you can see this. Allergies, preferences, reminders…',
  notesSaving: 'Saving…',
  notesSaved: 'Saved',
  activity: 'Activity',
  noActivity: 'No activity yet.',
  evCreated: 'Request received',
  evResubmitted: 'Submitted again',
  evStatus: '{from} → {to}',
  evContacted: 'You reached out ({channel}: {kind})',
  evNote: 'Note',
  evMerged: 'Merged into another request',
  evMergedIn: 'Duplicates merged into this request',
  evTrashed: 'Moved to Trash',
  evRestored: 'Restored from Trash',
  evRescheduled: 'Time changed',
  actConfirm: 'Confirm',
  actSuggest: 'Suggest another time',
  actDecline: 'Decline',
  actComplete: 'Mark completed',
  actNoShow: 'Mark no-show',
  actArchive: 'Archive',
  actFollowUp: 'Follow up',
  actReopen: 'Reopen',
  actCancelAppt: 'Cancel appointment',
  actMarkRead: 'Mark read',
  actMarkUnread: 'Mark unread',
  actDelete: 'Delete',
  actRestore: 'Restore',
  actDeleteForever: 'Delete permanently',
  actReminder: 'Send reminder',
  actRequestReview: 'Request a review',
  actMore: 'More actions',
  actExportCsv: 'Export CSV',
  actDownloadIcs: 'Add to calendar (.ics)',
  actAi: 'AI assist',
  confirmTitle: 'Confirm appointment',
  confirmFor: 'Confirm for',
  confirmAndText: 'Confirm & open text',
  confirmAndEmail: 'Confirm & open email',
  confirmOnly: 'Confirm without a message',
  chooseTime: 'Choose a time',
  anotherTime: 'Another time…',
  suggestTitle: 'Suggest another time',
  suggestHint: 'Pick up to 3 open slots to offer the client.',
  nextOpen: 'Next open slots',
  noOpenSlots: 'No open slots in the next weeks. Adjust hours in Contact.',
  openMessages: 'Open Messages',
  openEmail: 'Open email',
  openInstagram: 'Open Instagram',
  messagePreview: 'Message',
  editMessage: 'Edit before sending — nothing is sent automatically.',
  declineTitle: 'Decline request',
  declineHint: 'The client gets your message; the request moves to Declined.',
  deleteTitle: 'Delete request?',
  deleteBody: 'It moves to Trash for 30 days, then it’s gone.',
  deletedToast: 'Moved to Trash',
  restoredToast: 'Restored',
  purgeTitle: 'Delete permanently?',
  purgeBody: 'This cannot be undone.',
  conflictConfirmed: 'Overlaps a confirmed appointment with {name}',
  conflictPending: 'Overlaps a pending request from {name}',
  conflictOutside: 'Outside business hours',
  conflictBlackout: 'Falls on a closed day',
  conflictBlocked: 'Overlaps blocked time',
  duplicatesTitle: 'Submissions',
  duplicatesHint: 'The client sent this {n} times. Only one card is shown; nothing was deleted.',
  aiSummary: 'Summary',
  aiDraft: 'Draft reply',
  aiGenerate: 'Draft with AI',
  aiWorking: 'Thinking…',
  aiUseDraft: 'Use this draft',
  bulkMarkRead: 'Mark read',
  bulkArchive: 'Archive',
  bulkDelete: 'Delete',
  calDay: 'Day',
  calWeek: 'Week',
  calToday: 'Today',
  calPrev: 'Previous',
  calNext: 'Next',
  calPending: 'Pending',
  calConfirmed: 'Confirmed',
  calBlocked: 'Blocked',
  calClosed: 'Closed',
  calNothing: 'Nothing scheduled',
  calBlockTime: 'Block off time',
  clientsSearch: 'Search clients',
  clientRequests: 'Requests',
  clientVisits: 'Visits',
  clientUpcoming: 'Upcoming',
  clientNone: 'No clients yet',
  clientNoneBody: 'Clients appear here once booking requests come in.',
  clientSince: 'Client since',
  emptyInboxTitle: 'Inbox zero ✦',
  emptyInboxBody: 'New booking requests from the website will show up here.',
  emptySegment: 'Nothing here',
  emptySegmentBody: 'Requests move here as their status changes.',
  emptySearch: 'No matches for “{q}”',
  emptySearchBody: 'Try a name, phone number, email or service.',
  trashTitle: 'Trash',
  trashIntro: 'Deleted items stay here for {n} days, then are removed permanently.',
  trashEmpty: 'Trash is empty',
  trashEmptyBody: 'Deleted requests, reviews and messages appear here.',
  showTrash: 'Trash',
  newRequestsHint: '{n} new',
  markAllRead: 'Mark all read',
  expiredHint: 'The preferred time has passed.',
  followUpHint: 'Ask if they’d like a new time.',
  contactedHint: 'You’ve reached out. Waiting on the client.',
  perPage: 'per page',
  loadMore: 'Load more',
  csvExported: 'CSV downloaded',
  bookingUnnamed: 'No name given',
  lang_en: 'English',
  lang_uk: 'Ukrainian',
  lang_es: 'Spanish',
  customTime: 'Custom time',
  selectMode: 'Select',
  cancelSelect: 'Cancel selection',
  timezoneNote: 'Times shown in {tz}',
  weekOf: 'Week of {date}',
  submissionsList: 'All submissions',
  submittedAgo: 'Submitted {when}',
  noBookingsInRange: 'No requests in this range',
  openInCalendar: 'Open in calendar',
  sendConfirmation: 'Send confirmation',
  timeForAppointment: 'Appointment time',
  unknownService: 'Not specified',
  clientLangHint: 'Messages use the language the client used on the site.',
  nothingToShow: 'Nothing to show',
};

const uk: typeof en = {
  studioAdmin: 'Адмін студії',
  adminTitle: 'Адмін',
  navDashboard: 'Панель',
  navReviews: 'Відгуки',
  navServices: 'Послуги',
  navBio: 'Біо',
  navGallery: 'Галерея',
  navBrands: 'Бренди',
  navBookings: 'Записи',
  navMessages: 'Повідомлення',
  navContact: 'Контакти',
  navDomain: 'Домен',
  navSettings: 'Налаштування',
  navTrash: 'Кошик',
  navMore: 'Ще',
  groupOverview: 'Огляд',
  groupInbox: 'Вхідні',
  groupWebsite: 'Сайт',
  groupSetup: 'Налаштування',
  viewWebsite: 'Переглянути сайт',
  website: '← Сайт',
  account: 'Обліковий запис',
  signedInAs: 'Ви увійшли як',
  logout: 'Вийти',
  adminLanguage: 'Мова адмінки',
  dbUpdateTitle: 'Потрібне оновлення бази даних',
  dbUpdateBody:
    'Виконайте supabase/migrations/20260916_admin_redesign.sql у SQL-редакторі Supabase, щоб увімкнути статуси, нотатки, кошик і нові поля форми запису. До того цей екран працює в режимі сумісності.',

  loading: 'Завантаження…',
  retry: 'Повторити',
  errorTitle: 'Щось пішло не так',
  errorBody: 'Не вдалося завантажити. Перевірте з’єднання і спробуйте ще раз.',
  close: 'Закрити',
  back: 'Назад',
  done: 'Готово',
  undo: 'Скасувати дію',
  copy: 'Копіювати',
  copied: 'Скопійовано',
  search: 'Пошук',
  filters: 'Фільтри',
  clearFilters: 'Скинути фільтри',
  apply: 'Застосувати',
  select: 'Вибрати',
  selectAll: 'Вибрати всі',
  selectedCount: 'Вибрано: {n}',
  refresh: 'Оновити',
  saveChanges: 'Зберегти зміни',
  saved: 'Збережено',
  unsavedTitle: 'Незбережені зміни',
  unsavedBody: 'Є зміни, які ще не збережено. Усе одно вийти?',
  leave: 'Вийти',
  stay: 'Залишитись',
  toastSaved: '✓ Збережено',
  toastError: 'Не вдалося зберегти. Спробуйте ще раз.',
  toastUpdated: '✓ Оновлено',
  yes: 'Так',
  no: 'Ні',
  none: 'Немає',
  optional: 'Необов’язково',
  required: 'Обов’язково',
  showMore: 'Показати більше',
  showLess: 'Згорнути',
  today: 'Сьогодні',
  tomorrow: 'Завтра',
  yesterday: 'Вчора',
  noDate: 'Без дати',
  timeNotChosen: 'час не обрано',
  save: 'Зберегти',
  cancel: 'Скасувати',
  add: 'Додати',
  edit: 'Редагувати',
  delete: 'Видалити',
  replace: 'Замінити',
  remove: 'Прибрати',
  uploadImage: 'Завантажити фото',
  uploading: 'Завантаження…',
  livePreview: 'Попередній перегляд',
  weekdayShort: ['Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  weekdayLong: ['Неділя', 'Понеділок', 'Вівторок', 'Середа', 'Четвер', 'П’ятниця', 'Субота'],

  signIn: 'Вхід',
  signInSubtitle: 'Доступ лише для авторизованих',
  emailPlaceholder: 'Email',
  password: 'Пароль',
  passwordPlaceholder: 'Пароль',
  loginBtn: 'Увійти',
  signingIn: 'Вхід…',
  incorrectPassword: 'Невірний email або пароль',
  notAuthorized: 'Цей акаунт не має доступу до адмінпанелі.',
  checkingSession: 'Перевірка сесії…',

  bookingsTitle: 'Записи',
  bookingsIntro: 'Запити з кнопки «Записатися» на сайті.',
  viewInbox: 'Вхідні',
  viewCalendar: 'Календар',
  viewClients: 'Клієнти',
  segNeedsAction: 'Потребують дії',
  segConfirmed: 'Підтверджені',
  segPast: 'Минулі',
  segArchived: 'Архів',
  segAll: 'Усі',
  sortNeedsFirst: 'Спочатку ті, що потребують дії',
  sortNewest: 'Спочатку нові',
  sortLabel: 'Сортування',
  searchBookings: 'Пошук за ім’ям, телефоном, email або послугою',
  filterStatus: 'Статус',
  filterService: 'Послуга',
  filterFrom: 'Від',
  filterTo: 'До',
  filterAnyStatus: 'Будь-який статус',
  filterAnyService: 'Будь-яка послуга',
  filterDateRange: 'Бажана дата',
  statusNew: 'Новий',
  statusContacted: 'На зв’язку',
  statusConfirmed: 'Підтверджено',
  statusCompleted: 'Завершено',
  statusDeclined: 'Відхилено',
  statusCancelled: 'Скасовано',
  statusNoShow: 'Не прийшов',
  statusArchived: 'В архіві',
  badgeReplyToday: 'Відповісти сьогодні',
  badgeExpired: 'Прострочено',
  badgeConflict: 'Конфлікт часу',
  badgeReturning: 'Постійний · {n} візитів',
  badgeReturningRequests: 'Постійний · {n} запитів',
  badgeNewClient: 'Новий клієнт',
  badgeSubmissions: '×{n} заявок',
  badgeUnread: 'Непрочитано',
  badgeNoTime: 'Час не обрано',
  badgeOutsideHours: 'Поза робочими годинами',
  badgeClosedDay: 'Зачинено в цей день',
  summaryReplyToday: '{n} потребують відповіді сьогодні',
  summaryDuplicates: '{n} дублікатів об’єднано',
  summaryConflicts: '{n} конфліктів часу',
  summaryConfirmedWeek: '{n} підтверджено цього тижня',
  summaryAllClear: 'Усе оброблено ✦',
  preferred: 'Бажано',
  submitted: 'Надіслано',
  via: 'через',
  methodSms: 'SMS',
  methodInstagram: 'Instagram',
  methodEmail: 'Email',
  methodCall: 'Дзвінок',
  requestDetails: 'Запит',
  client: 'Клієнт',
  contact: 'Контакти',
  actionText: 'Написати',
  actionCall: 'Подзвонити',
  actionEmail: 'Email',
  noPhoneCaptured: 'Телефон не збережено (старий запит). Запитайте його у відповіді.',
  service: 'Послуга',
  price: 'Ціна',
  duration: 'Тривалість',
  minutesShort: '{n} хв',
  preferredTime: 'Бажаний час',
  alsoOk: 'Також підходить',
  optionsFromSubmissions: 'Час із {n} заявок',
  clientMessage: 'Повідомлення клієнта',
  siteLanguage: 'Мова сайту',
  clientHistory: 'Історія клієнта',
  requestsCount: 'Запитів: {n}',
  visitsCount: 'Візитів: {n}',
  upcomingCount: 'Майбутніх: {n}',
  lastService: 'Остання послуга',
  lastVisit: 'Останній візит',
  firstRequest: 'Перший запит',
  privateNotes: 'Приватні нотатки',
  notesPlaceholder: 'Бачите лише ви. Алергії, побажання, нагадування…',
  notesSaving: 'Збереження…',
  notesSaved: 'Збережено',
  activity: 'Активність',
  noActivity: 'Поки що нічого.',
  evCreated: 'Запит отримано',
  evResubmitted: 'Надіслано повторно',
  evStatus: '{from} → {to}',
  evContacted: 'Ви зв’язалися ({channel}: {kind})',
  evNote: 'Нотатка',
  evMerged: 'Об’єднано з іншим запитом',
  evMergedIn: 'Дублікати об’єднано в цей запит',
  evTrashed: 'Переміщено в кошик',
  evRestored: 'Відновлено з кошика',
  evRescheduled: 'Час змінено',
  actConfirm: 'Підтвердити',
  actSuggest: 'Запропонувати інший час',
  actDecline: 'Відхилити',
  actComplete: 'Позначити завершеним',
  actNoShow: 'Не прийшов',
  actArchive: 'В архів',
  actFollowUp: 'Нагадати про себе',
  actReopen: 'Відкрити знову',
  actCancelAppt: 'Скасувати запис',
  actMarkRead: 'Позначити прочитаним',
  actMarkUnread: 'Позначити непрочитаним',
  actDelete: 'Видалити',
  actRestore: 'Відновити',
  actDeleteForever: 'Видалити назавжди',
  actReminder: 'Надіслати нагадування',
  actRequestReview: 'Попросити відгук',
  actMore: 'Більше дій',
  actExportCsv: 'Експорт CSV',
  actDownloadIcs: 'Додати в календар (.ics)',
  actAi: 'AI-помічник',
  confirmTitle: 'Підтвердити запис',
  confirmFor: 'Підтвердити на',
  confirmAndText: 'Підтвердити й написати',
  confirmAndEmail: 'Підтвердити й надіслати email',
  confirmOnly: 'Підтвердити без повідомлення',
  chooseTime: 'Оберіть час',
  anotherTime: 'Інший час…',
  suggestTitle: 'Запропонувати інший час',
  suggestHint: 'Оберіть до 3 вільних слотів, щоб запропонувати клієнту.',
  nextOpen: 'Найближчі вільні слоти',
  noOpenSlots: 'Немає вільних слотів найближчими тижнями. Змініть години в «Контактах».',
  openMessages: 'Відкрити Повідомлення',
  openEmail: 'Відкрити пошту',
  openInstagram: 'Відкрити Instagram',
  messagePreview: 'Повідомлення',
  editMessage: 'Відредагуйте перед надсиланням — нічого не надсилається автоматично.',
  declineTitle: 'Відхилити запит',
  declineHint: 'Клієнт отримає ваше повідомлення; запит перейде у «Відхилено».',
  deleteTitle: 'Видалити запит?',
  deleteBody: 'Він переміститься в кошик на 30 днів, після чого зникне.',
  deletedToast: 'Переміщено в кошик',
  restoredToast: 'Відновлено',
  purgeTitle: 'Видалити назавжди?',
  purgeBody: 'Цю дію неможливо скасувати.',
  conflictConfirmed: 'Перетинається з підтвердженим записом: {name}',
  conflictPending: 'Перетинається із запитом від {name}',
  conflictOutside: 'Поза робочими годинами',
  conflictBlackout: 'Припадає на вихідний день',
  conflictBlocked: 'Перетинається із заблокованим часом',
  duplicatesTitle: 'Заявки',
  duplicatesHint: 'Клієнт надіслав це {n} рази. Показано одну картку; нічого не видалено.',
  aiSummary: 'Стисло',
  aiDraft: 'Чернетка відповіді',
  aiGenerate: 'Створити чернетку з AI',
  aiWorking: 'Думаю…',
  aiUseDraft: 'Використати чернетку',
  bulkMarkRead: 'Прочитано',
  bulkArchive: 'В архів',
  bulkDelete: 'Видалити',
  calDay: 'День',
  calWeek: 'Тиждень',
  calToday: 'Сьогодні',
  calPrev: 'Назад',
  calNext: 'Далі',
  calPending: 'Очікує',
  calConfirmed: 'Підтверджено',
  calBlocked: 'Заблоковано',
  calClosed: 'Зачинено',
  calNothing: 'Нічого не заплановано',
  calBlockTime: 'Заблокувати час',
  clientsSearch: 'Пошук клієнтів',
  clientRequests: 'Запити',
  clientVisits: 'Візити',
  clientUpcoming: 'Майбутні',
  clientNone: 'Клієнтів поки немає',
  clientNoneBody: 'Клієнти з’являться тут після перших запитів на запис.',
  clientSince: 'Клієнт з',
  emptyInboxTitle: 'Вхідні порожні ✦',
  emptyInboxBody: 'Нові запити з сайту з’являтимуться тут.',
  emptySegment: 'Тут нічого немає',
  emptySegmentBody: 'Запити потрапляють сюди зі зміною статусу.',
  emptySearch: 'Нічого не знайдено за запитом «{q}»',
  emptySearchBody: 'Спробуйте ім’я, номер телефону, email або послугу.',
  trashTitle: 'Кошик',
  trashIntro: 'Видалені елементи зберігаються тут {n} днів, потім видаляються назавжди.',
  trashEmpty: 'Кошик порожній',
  trashEmptyBody: 'Видалені запити, відгуки та повідомлення з’являтимуться тут.',
  showTrash: 'Кошик',
  newRequestsHint: 'нових: {n}',
  markAllRead: 'Позначити всі прочитаними',
  expiredHint: 'Бажаний час уже минув.',
  followUpHint: 'Запитайте, чи підійде інший час.',
  contactedHint: 'Ви зв’язалися. Чекаємо на клієнта.',
  perPage: 'на сторінці',
  loadMore: 'Показати ще',
  csvExported: 'CSV завантажено',
  bookingUnnamed: 'Без імені',
  lang_en: 'Англійська',
  lang_uk: 'Українська',
  lang_es: 'Іспанська',
  customTime: 'Інший час',
  selectMode: 'Вибрати',
  cancelSelect: 'Скасувати вибір',
  timezoneNote: 'Час показано для {tz}',
  weekOf: 'Тиждень від {date}',
  submissionsList: 'Усі заявки',
  submittedAgo: 'Надіслано {when}',
  noBookingsInRange: 'Немає запитів у цьому діапазоні',
  openInCalendar: 'Відкрити в календарі',
  sendConfirmation: 'Надіслати підтвердження',
  timeForAppointment: 'Час запису',
  unknownService: 'Не вказано',
  clientLangHint: 'Повідомлення складаються мовою, якою клієнт користувався на сайті.',
  nothingToShow: 'Нічого показувати',
};

export const ADMIN_DICT = { en, uk };
export type AdminDict = typeof en;
